### ISSUE TITLE
import path incorrect after yarn build after folllowing readme

### ISSUE THREAD

**Issue by imgregduh** [bumble-org/rollup-plugin-chrome-extension#10]
**Describe the bug**
I followed the read to get set up then I noticed that it was throwing an exception that it couldnt find one of the bundled files then I saw that the path was wrong for a win OS 

This was generated
`import('..\background.js').then(triggerEvents);`

This is what should have been generated 
`import('../background.js').then(triggerEvents);`

**To Reproduce**
1. Follow readme instructions
2. `yarn build`
3. Try to load to chrome

**Expected behavior**
I expect the path to be compatible with whichever OS I am using.

**Screenshots**
![image](https://user-images.githubusercontent.com/5440162/67157021-9e627600-f2eb-11e9-81a0-17915f95a742.png)

**Desktop (please complete the following information):**
 - OS: win 10

**Additional context**
I had to install the ubuntu subsystem on to my windows 10 machine and ran `yarn build` in the mean time and it generates the path fine.

**Comment by AmySteam** [comment]
Thank you for bringing this to our attention! 👍 We mostly Linux so we had not ran into this issue.
It looks like we are using the system slash to generate the dynamic import url. We will switch to always using the forward slash for this path.

**Comment by imgregduh** [comment]
That's good to know, I am glad this is finally getting some attention.
