### ISSUE TITLE
Error when rollup.config has more than one input file

### ISSUE THREAD

**Issue by rafalkrupinski** [bumble-org/rollup-plugin-chrome-extension#27]
**Describe the bug**
I have a bunch of images that are handled from JS (no img tag in html). Rollup doesn't include them in the dist directory.
When I add them to 'input' in rollup.config  I get this error
```
[!] TypeError: RollupOptions.input must be a single Chrome extension manifest.
```

**To Reproduce**
create rollup.config with
```js
export default {
    input    : ['src/manifest.json'],
    ...
}
```

**Expected behavior**
Input can be declared as an array, and all entries other than manifest.json are processed as rollup normally does.

**Comment by jacksteamdev** [comment]
Thanks for the great issue! 👍

Typically we use [`@rollup/plugin-image`](https://www.npmjs.com/package/@rollup/plugin-image) or [something equivalent](https://www.npmjs.com/package/rollup-plugin-image-files) to bundle our images. This way you can import them in JS (as you would in `create-react-app`). The goal is that everything just works without needing to update the Rollup config.

Another option is to put any files that are not bundled automatically in `manifest.json` in `web_accessible_resources`.

We've tried to limit the amount of config that is required in `rollup.config.js`. IME, it makes for faster development.

**Comment by jacksteamdev** [comment]
@rafalkrupinski I've updated my answer with an example that I used in a recent project.

**Comment by rafalkrupinski** [comment]
@jacksteamdev Thank you for your answer.
It's for options_ui, so using web_accessible_resources would be a hack, but surely work :)
I used rollup-plugin-cpy in the end. Thank you for that hint on using a plugin.

**Comment by jacksteamdev** [comment]
@rafalkrupinski Glad I could help a little bit! Does the `options_ui` html page bundle correctly?

**Comment by rafalkrupinski** [comment]
Yes, looks alright, though I don't have any es6 imports. html mentions a css and js and they're both included. Also my workaround for this problem was to include 
```html
<div style="display='none'">
<img ...>
</div>
```
with all the images and it worked, but maintaining it would be as nice ;)

Cheers.
