### ISSUE TITLE
Support for `devtools_page` field in `manifest.json`

### ISSUE THREAD

**Issue by witcher-development** [bumble-org/rollup-plugin-chrome-extension#28]
@jacksteamdev 
Please add support for `devtools_page` field in `manifest.json`. Currently, it just ignores it and can't handle devtools functionality of an extension.

It would be really nice! Say me if I can participate in it. It is important for my project.
I look forward to hearing!

**Comment by jacksteamdev** [comment]
That sounds like a great idea! PRs are welcome! Just make sure you add some tests. :)

Here's a good place to start:
https://github.com/bumble-org/rollup-plugin-chrome-extension/blob/d312efc5c669161cb7144ae2feffa0be0c96f84a/src/manifest-input/manifest-parser/index.ts#L72-L79

**Comment by jacksteamdev** [comment]
@witcher-development [This was released on npm in v2.2.0!](https://www.npmjs.com/package/rollup-plugin-chrome-extension)
