### ISSUE TITLE
Source maps don't work for typescript

### ISSUE THREAD

**Issue by stevenheidel** [bumble-org/rollup-plugin-chrome-extension#35]
**Describe the bug**
Source maps throw an error in the console:
`DevTools failed to load SourceMap: Could not load content for chrome-extension://dhkkfbogdjlaiokeknpkpdkogcahamhe/popup/popup.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**To Reproduce**
The following rollup.config.js:

```js
export default {
    input: 'src/manifest.json',
    output: {
        dir: 'dist',
        format: 'esm',
        sourcemap: true,
    },
    plugins: [
        chromeExtension(),
        simpleReloader(),
        typescript({include: 'src/**/*.ts', sourceMap: true}),
        resolve(),
        commonjs(),
    ],
}
```

**Expected behavior**
Source maps are linked automatically.

**Versions:**
 - OS: MacOS Catalina
 - Browser: Chrome 83

    "@rollup/plugin-commonjs": "^11.1.0",
    "@rollup/plugin-node-resolve": "^8.0.1",
    "@rollup/plugin-typescript": "^4.1.2",
    "rollup": "^1.32.1",
    "rollup-plugin-chrome-extension": "^2.2.1",
    "typescript": "^3.7.4",
    "webextension-polyfill-ts": "^0.12.0"

**Comment by jacksteamdev** [comment]
@stevenheidel Try using [inline sourcemaps](https://rollupjs.org/guide/en/#outputsourcemap) during development. Chrome won't load Chrome extension sourcemap _files_, but inline sourcemaps do work.

### Background

Chrome has always silently failed to load sourcemap files from the `chrome-extension://` URL scheme. Chrome v80 started reporting the `DevTools failed to load SourceMap` error.

This may change soon, as there is [a fix in the works](https://chromium-review.googlesource.com/c/chromium/src/+/2141899). Some security concerns are holding this back, so keep your fingers crossed.

Here are two relevant Chromium bugs tracking this: 

1. https://bugs.chromium.org/p/chromium/issues/detail?id=1052872#c14
2. https://bugs.chromium.org/p/chromium/issues/detail?id=1053535

**Comment by stevenheidel** [comment]
Setting `output.sourcemap` to `'inline'` works, thanks!

**Comment by tjx666** [comment]
for vite user, you need to set like this:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/41773861/221429380-8d3c022d-ae8a-4d90-a036-49eb50f7bef9.png">
